---
title: "practical_exercise_8 , Methods 3, 2021, autumn semester"
author: 'Alina Kereszt'
date: "17.11.2021"
output: pdf_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>


# Exercises and objectives

1) Load the magnetoencephalographic recordings and do some initial plots to understand the data  
2) Do logistic regression to classify pairs of PAS-ratings  
3) Do a Support Vector Machine Classification on all four PAS-ratings  

REMEMBER: In your report, make sure to include code that can reproduce the answers requested in the exercises below (__MAKE A KNITTED VERSION__)  
REMEMBER: This is Assignment 3 and will be part of your final portfolio   

```{python}
# load packages
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold
```


# EXERCISE 1 - Load the magnetoencephalographic recordings and do some initial plots to understand the data  

The files `megmag_data.npy` and `pas_vector.npy` can be downloaded here (http://laumollerandersen.org/data_methods_3/megmag_data.npy) and here (http://laumollerandersen.org/data_methods_3/pas_vector.npy)   

1) Load `megmag_data.npy` and call it `data` using `np.load`. You can use `join`, which can be imported from `os.path`, to create paths from different string segments
```{python}
# 'join' creates a handy, quick way to refer to a particular path, so you don't have to keep typing it out
# path = '~/GitHub/Coding/Methods 3/week_08'
# path = os.path.join(path, 'megmag_data.npy')

data = np.load('megmag_data.npy') # load data
```
    i. The data is a 3-dimensional array. The first dimension is number of repetitions of a visual stimulus , the second dimension is the number of sensors that record magnetic fields (in Tesla) that stem from neurons activating in the brain, and the third dimension is the number of time samples. How many repetitions, sensors and time samples are there?  
    ```{python}
data.shape # show shape of data; it is a téglatest!!!
# BASICALLY what you have is a big cube of values that are ONLY THE MEASUREMENTS. So far, the variables 'repetition', 'sensor' and 'timestamp' are only implied - they have not been created.
```
    ii. The time range is from (and including) -200 ms to (and including) 800 ms with a sample recorded every 4 ms. At time 0, the visual stimulus was briefly presented. Create a 1-dimensional array called `times` that represents this.  
    ```{python}
# In Python, you can refer to specific components of an element with square brackets ([])
# Specifying '0' means you want to extract the first element of that variable
# A colon (:) means you want everything
# You can also specify a specific row to start or end with, e.g. [:7] will take everything until the 8th variable
values = data[0, 0, :]
timestamps = np.arange(-200, 804, 4)
times = timestamps, values
```
    iii. Create the sensor covariance matrix $\Sigma_{XX}$: $$\Sigma_{XX} = \frac 1 N \sum_{i=1}^N XX^T$$ $N$ is the number of repetitions and $X$ has $s$ rows and $t$ columns (sensors and time), thus the shape is $X_{s\times t}$. Do the sensors pick up independent signals? (Use `plt.imshow` to plot the sensor covariance matrix)  
    ```{python}
# There are 102 sensors, so the covariance matrix is going to be 102 by 102
# To multiply an m×n matrix by an n×p matrix, the ns must be the same, and the result is an m×p matrix
# Here we multiply matrices 102x251 and 251x102 in size
# 'np.zeros' just creates an empty matrix to receive values
mat_1_1a = np.zeros(shape = (102, 102))
# Since our data is basically matrices stacked on top of each other, we can loop through each repetition and apply the formula
for i in range(0, 681):
  mat_1_1a += data[i, :, :] @ data[i, :, :].T
covmat_1_1a = mat_1_1a/682

import matplotlib.pyplot as plt
plt.imshow(covmat_1_1a)
plt.colorbar()
plt.show()
```
    iv. Make an average over the repetition dimension using `np.mean` - use the `axis` argument. (The resulting array should have two dimensions with time as the first and magnetic field as the second) 
    ```{python}
rep_means = np.mean(data, axis = 0) # since repetition is the 1st dimension
rep_means.shape
# shape isn't right; it needs to get rotated 270 degrees so the timestamps are in order
rep_means = np.rot90(rep_means, k = 3, axes = (0, 1)) # or swapaxes
rep_means.shape
```
    v. Plot the magnetic field (based on the average) as it evolves over time for each of the sensors (a line for each) (time on the x-axis and magnetic field on the y-axis). Add a horizontal line at $y = 0$ and a vertical line at $x = 0$ using `plt.axvline` and `plt.axhline`  
    ```{python}
# Time ended up along the second dimension for me and idk how to fix it
# I add my timestamps as 103rd column along the sensor axis (i.e. concatenate a 1d array along the 2nd axis, time, since that is identical in length)
# timestamps = np.arange(-200, 804, 4)
# test = rep_means[0, :]
# plt.figure()
# plt.plot(timestamps, test, 'b-')
# plt.show()

plt.figure()
for i in range(0, 102):
  sensor_values = rep_means[:, i]
  plt.plot(timestamps, sensor_values, 'm-', linewidth = 0.5)
plt.axvline(x = 0, color = 'k', linewidth = 0.5)
plt.axhline(y = 0, color = 'k', linewidth = 0.5)
plt.xlabel('Time (ms)')
plt.ylabel('Magnetic field (T)')
plt.title('Magnetic field by sensor through time')
plt.show()

# hehe a doodle
# plt.figure()
# plt.plot(rep_means[1], rep_means[0], 'b-')
# plt.show()

```
    vi. Find the maximal magnetic field in the average. Then use `np.argmax` and `np.unravel_index` to find the sensor that has the maximal magnetic field.  
    ```{python}
# Find the highest value:
rep_means.shape
max_mag_field = np.amax(rep_means)
max_mag_field

# Computers store info in a linear way. Each memory cell corresponds to a number. A block of memory can be addressed in terms of a base, which is the memory address of its first element, and the item index.
# Like how Arabic numbers have a base of 10. Take an array of numbers 10x7, whole numbers starting from 1. If we look for the linear index 27 (which in this case happens to contain the number 27), we would find that it is in the 3rd row, and in the seventh column, so its 2D index would be (2, 7).
# This function finds the linear index of the value we found for our maximal magnetic field:
linear_index = np.argmax(rep_means)
# And this one handily calculates the (in this case) 2D index of it - the second number of which will be our sensor!
sensor_2d_index = np.unravel_index(linear_index, (251, 102))
# It's sensor 28!
```
    vii. Plot the magnetic field for each of the repetitions (a line for each) for the sensor that has the maximal magnetic field. Highlight the time point with the maximal magnetic field in the average (as found in 1.1.v) using `plt.axvline`  
    ```{python}
# Isolate the data for sensor 28
sensor_pos = sensor_2d_index[1] - 1
sensor28 = data[:, sensor_pos, :]

# Find the timepoint at which the average is highest
find_time_array = np.rot90(rep_means, k = 1, axes = (0, 1))
find_time_linear = np.argmax(find_time_array)
find_time_2d = np.unravel_index(find_time_linear, (102, 251))
time_pos = find_time_2d[1] - 1

plt.figure()
for i in range(0, 682):
  sensor_values = sensor28[i, :]
  plt.plot(timestamps, sensor_values, 'm-', linewidth = 0.1)
plt.axvline(x = time_pos, color = 'k', linewidth = 0.5)
plt.xlabel('Time (ms)')
plt.ylabel('Magnetic field (T)')
plt.title('Magnetic field for sensor 28 through time by repetition')
plt.show()
```
    viii. Describe in your own words how the response found in the average is represented in the single repetitions. But do make sure to use the concepts _signal_ and _noise_ and comment on any differences on the range of values on the y-axis  

2) Now load `pas_vector.npy` (call it `y`). PAS is the same as in Assignment 2, describing the clarity of the subjective experience the subject reported after seeing the briefly presented stimulus  
```{python}
y = np.load('pas_vector.npy') # load data
```
    i. Which dimension in the `data` array does it have the same length as?  
```{python}
data.shape
y.shape # same length as the number of repetitions, i.e. one PAS-rating is given for each repetition
```
    ii. Now make four averages (As in Exercise 1.1.iii), one for each PAS rating, and plot the four time courses (one for each PAS rating) for the sensor found in Exercise 1.1.v
```{python}
# Extract linear index of places where each PAS-rating is 1, 2, 3 or 4 in y
# This will be the position along data[0] where we need to take the slice
a = np.where(y == 1)
b = np.where(y == 2)
c = np.where(y == 3)
d = np.where(y == 4) # find positions
a = a[0]
b = b[0]
c = c[0]
d = d[0] # for some reason you need to extract the values from the array into a list to slice without adding extra dimensions
pas1 = data[a, :, :]
pas2 = data[b, :, :]
pas3 = data[c, :, :]
pas4 = data[d, :, :] # slice away!

# Find mean
pas1_mean = np.mean(pas1, axis = 0)
pas2_mean = np.mean(pas2, axis = 0)
pas3_mean = np.mean(pas3, axis = 0)
pas4_mean = np.mean(pas4, axis = 0)

plt.figure()
plt.plot(timestamps, pas1_mean[sensor_pos,], 'm-', linewidth = 0.5)
plt.plot(timestamps, pas2_mean[sensor_pos,], 'c-', linewidth = 0.5)
plt.plot(timestamps, pas3_mean[sensor_pos,], 'r-', linewidth = 0.5)
plt.plot(timestamps, pas4_mean[sensor_pos,], 'b-', linewidth = 0.5)
plt.axvline(x = 0, color = 'k', linewidth = 0.5)
plt.axhline(y = 0, color = 'k', linewidth = 0.5)
plt.xlabel('Time (ms)')
plt.ylabel('Magnetic field (T)')
plt.title('Magnetic field for Sensor 28 through time by PAS-rating')
plt.legend(['PAS1', 'PAS2', 'PAS3', 'PAS4'])
plt.show()
```
    iii. Notice that there are two early peaks (measuring visual activity from the brain), one before 200 ms and one around 250 ms. Describe how the amplitudes of responses are related to the four PAS-scores. Does PAS 2 behave differently than expected? 

# EXERCISE 2 - Do logistic regression to classify pairs of PAS-ratings  

1) Now, we are going to do Logistic Regression with the aim of classifying the PAS-rating given by the subject
    i. We'll start with a binary problem - create a new array called `data_1_2` that only contains PAS responses 1 and 2. Similarly, create a `y_1_2` for the target vector  
```{python}
pos_1 = np.where(y == 1) 
pos_1 = pos_1[0] 
pos_2 = np.where(y == 2) 
pos_2 = pos_2[0]
pos_1_2 = np.concatenate([pos_1, pos_2]) # OR np.stack((pos_1, pos_2))
pos_1_2 = np.sort(pos_1_2)

data_1_2 = data[pos_1_2, :, :]
y_1_2 = y[pos_1_2]
```
    ii. Scikit-learn expects our observations (`data_1_2`) to be in a 2d-array, which has samples (repetitions) on dimension 1 and features (predictor variables) on dimension 2. Our `data_1_2` is a three-dimensional array. Our strategy will be to collapse our two last dimensions (sensors and time) into one dimension, while keeping the first dimension as it is (repetitions). Use `np.reshape` to create a variable `X_1_2` that fulfils these criteria.  
```{python}
shape = data_1_2.shape
time_by_sensor = shape[1] * shape[2]
X_1_2 = np.reshape(data_1_2, (shape[0], time_by_sensor)) # 1st dimension intact, 2nd and 3rd collapsed into single dimension equal to the product of their length
# X_1_2.shape
```
    iii. Import the `StandardScaler` and scale `X_1_2`  
```{python}
sc = StandardScaler() # assign function to an object to make it easier to refer to
sc.fit(X_1_2) # estimate sample mean and standard deviation for each feature dimension
X_1_2_std = sc.transform(X_1_2) # standardize the data through gradient descent
```
    iv. Do a standard `LogisticRegression` - can be imported from `sklearn.linear_model` - make sure there is no `penalty` applied  
```{python}
# don't we need to split the dataset into train and test lol
logR = LogisticRegression(penalty = 'none') # assign function to object
logR.fit(X_1_2_std, y_1_2) # fit the model based on scaled X and y
```
    v. Use the `score` method of `LogisticRegression` to find out how many labels were classified correctly. Are we overfitting? Besides the score, what would make you suspect that we are overfitting?  
```{python}
logR.score(X_1_2_std, y_1_2)
```
    vi. Now apply the _L1_ penalty instead - how many of the coefficients (`.coef_`) are non-zero after this?  
```{python}
logR_l1 = LogisticRegression(penalty = 'l1', solver = 'saga') # assign function to object
# The following line throws an error with the default solver (which is the algorithm used in the optimization problem). Documentation suggests that we can use either 'liblinear' or 'saga', with 'saga' being better for large datasets, so this is what I chose. BUT I have no bloody clue what it does.
logR_l1.fit(X_1_2_std, y_1_2) # fit the model based on scaled X and y
logR_l1.score(X_1_2_std, y_1_2)
# ??????????????????????????????????????????? wtf is going on idk how to interpret this shit there is no text on it
```
    vii. Create a new reduced $X$ that only includes the non-zero coefficients - show the covariance of the non-zero features (two covariance matrices can be made; $X_{reduced}X_{reduced}^T$ or $X_{reduced}^TX_{reduced}$ (you choose the right one)) . Plot the covariance of the features using `plt.imshow`. Compared to the plot from 1.1.iii, do we see less covariance?  
```{python}
# bitch please
```
2) Now, we are going to build better (more predictive) models by using cross-validation as an outcome measure    
    i. Import `cross_val_score` and `StratifiedKFold` from `sklearn.model_selection`  
    ii. To make sure that our training data sets are not biased to one target (PAS) or the other, create `y_1_2_equal`, which should have an equal number of each target. Create a similar `X_1_2_equal`. The function `equalize_targets_binary` in the code chunk associated with Exercise 2.2.ii can be used. Remember to scale `X_1_2_equal`!  
    ```{python}
# Function:
def equalize_targets_binary(data, y):
    np.random.seed(7)
    targets = np.unique(y) ## find the number of targets, i.e. possible values y can take on
    if len(targets) > 2:
        raise NameError("can't have more than two targets")
    counts = list() #initialize list
    indices = list() #initialize list
    for target in targets:
        counts.append(np.sum(y == target)) # 
        indices.append(np.where(y == target)[0]) ## find their indices
    min_count = np.min(counts)
    # randomly choose trials
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count,replace=False)
    
    # create the new data sets
    new_indices = np.concatenate((first_choice, second_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y
  
equalize_targets_binary(X_1_2, y_1_2)
```
    iii. Do cross-validation with 5 stratified folds doing standard `LogisticRegression` (See Exercise 2.1.iv) 
    ```{python}

```
    iv. Do L2-regularisation with the following `Cs=  [1e5, 1e1, 1e-5]`. Use the same kind of cross-validation as in Exercise 2.2.iii. In the best-scoring of these models, how many more/fewer predictions are correct (on average)?  
    ```{python}

```
    v. Instead of fitting a model on all `n_sensors * n_samples` features, fit  a logistic regression (same kind as in Exercise 2.2.iv (use the `C` that resulted in the best prediction)) for __each__ time sample and use the same cross-validation as in Exercise 2.2.iii. What are the time points where classification is best? Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)  
    ```{python}

```
    vi. Now do the same, but with L1 regression - set `C=1e-1` - what are the time points when classification is best? (make a plot)?  
    ```{python}

```
    vii. Finally, fit the same models as in Exercise 2.2.vi but now for `data_1_4` and `y_1_4` (create a data set and a target vector that only contains PAS responses 1 and 4). What are the time points when classification is best? Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)  
    ```{python}

```
3) Is pairwise classification of subjective experience possible? Any surprises in the classification accuracies, i.e. how does the classification score fore PAS 1 vs 4 compare to the classification score for PAS 1 vs 2?  


```{python, eval=FALSE}
# Exercise 2.2.ii
def equalize_targets_binary(data, y):
    np.random.seed(7)
    targets = np.unique(y) ## find the number of targets
    if len(targets) > 2:
        raise NameError("can't have more than two targets")
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target)) ## find the number of each target
        indices.append(np.where(y == target)[0]) ## find their indices
    min_count = np.min(counts)
    # randomly choose trials
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count,replace=False)
    
    # create the new data sets
    new_indices = np.concatenate((first_choice, second_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y
```

# EXERCISE 3 - Do a Support Vector Machine Classification on all four PAS-ratings  
1) Do a Support Vector Machine Classification  
    i. First equalize the number of targets using the function associated with each PAS-rating using the function associated with Exercise 3.1.i  
    ```{python}

```
    ii. Run two classifiers, one with a linear kernel and one with a radial basis (other options should be left at their defaults) - the number of features is the number of sensors multiplied the number of samples. Which one is better predicting the category?
    ```{python}

```
    iii. Run the sample-by-sample analysis (similar to Exercise 2.2.v) with the best kernel (from Exercise 3.1.ii). Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)
    ```{python}

```
    iv. Is classification of subjective experience possible at around 200-250 ms?  
    ```{python}

```
2) Finally, split the equalized data set (with all four ratings) into a training part and test part, where the test part if 30 % of the trials. Use `train_test_split` from `sklearn.model_selection`  
```{python}

```
    i. Use the kernel that resulted in the best classification in Exercise 3.1.ii and `fit`the training set and `predict` on the test set. This time your features are the number of sensors multiplied by the number of samples.
    ```{python}

```
    ii. Create a _confusion matrix_. It is a 4x4 matrix. The row names and the column names are the PAS-scores. There will thus be 16 entries. The PAS1xPAS1 entry will be the number of actual PAS1, $y_{pas1}$ that were predicted as PAS1, $\hat y_{pas1}$. The PAS1xPAS2 entry will be the number of actual PAS1, $y_{pas1}$ that were predicted as PAS2, $\hat y_{pas2}$ and so on for the remaining 14 entries.  Plot the matrix
    ```{python}

```
    iii. Based on the confusion matrix, describe how ratings are misclassified and if that makes sense given that ratings should measure the strength/quality of the subjective experience. Is the classifier biased towards specific ratings?  
    ```{python}

```
    
```{python, eval=FALSE}

def equalize_targets(data, y):
    np.random.seed(7)
    targets = np.unique(y)
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target))
        indices.append(np.where(y == target)[0])
    min_count = np.min(counts)
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count, replace=False)
    third_choice = np.random.choice(indices[2], size=min_count, replace=False)
    fourth_choice = np.random.choice(indices[3], size=min_count, replace=False)
    
    new_indices = np.concatenate((first_choice, second_choice,
                                 third_choice, fourth_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y

```